### PR TITLE
Development

### PR DESCRIPTION
**Pull request by torresmvl**
Sorry for being late, mate! Had long weeks since we last spoked.

Improvements:
- Smaller image footprint (from roughly **1Gb** to **268Mb**) -> `FROM node:13.0.1-stretch-slim` is the big player here
- Run as non-root, note that this time i've taken advantage of default **node** user
---
### Bringing to discussion:
do you plan to support multi-arch builds for your repo? i've been using without issues on my RPi B v1 (armv6), HA with Docker Swarm (every pi on farm has its octoprint instances and at least 1 octofarm instance. Those are mixed rpi versions, (armv6/v7/v8), but i have to build manualy to keep my images up to date with **master**.
If there is interest, i could share my codes to build & push these multi-arch builds.

Again, thank you for this app! Now looking torwards the monolithic image!

### CODE REVIEW

**Comment by NotExpectedYet** [comment]
Oooo hello, your back with goodies! 

No drama man, big thanks for all this. Feeling like i should send you a OctoFarm t-shirt or something. If you want, drop me an email will happily sort one out for you. 

So multi-arch stuff for me is currently only limited by damn mongodb. There's no qualms in me about producing dockers and stuff but with the work on 1.2 I won't be giving it much focus so your totally welcome to if that's what you'd like. I'll happily merge any of that if it makes it easier on your multi-arch setup. 

If you manage to get the monolithic mult-arch, I'll send you a damn Jumper and Pillow with your t-shirt. That's something I've been nagged at for ages but I just haven't had the time to actually sit down and try to compile mongo community on it. Please... do!

**Comment by torresmvl** [comment]
> 
> 
> If you manage to get the monolithic mult-arch, I'll send you a damn Jumper and Pillow with your t-shirt. That's something I've been nagged at for ages but I just haven't had the time to actually sit down and try to compile mongo community on it. Please... do!

Oh! That would be interesting... But i'm afraid that mongodb does not offer native support for i386 or any other x86 arch. But i will try :om:

My current approach relies in detaching the mongo process from the node environment. I'm using the _**mongoDb Atlas**_ service at the farm, it's free and very convenient for me.

For dev environment, i'm using this simple `docker-compose.yml`:

```YAML
---
version: "3"
services:
  octofarm:
    image: octofarm/octofarm:alpine-latest # the main image also works here
    networks:
      - octofarm_private
    ports:
      - "4000:4000"
    environment: 
      MONGO: mongodb://mongodb:27017/octofarm
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    networks:
      - octofarm_private
    ports:
      - "27017"
    command: mongod --dbpath /data/db

networks:
  octofarm_private:
    driver: overlay

```
Now looking for ways to reduce the monolithic image, too many layers to pull and extract!

ps: mailing you :love_you_gesture:

**Comment by NotExpectedYet** [comment]
Aye understandable and yeah it's more for less knowledgeable users the monolithic image and was another donation so probably followed the format from the first. 

Do what you can man it's already awesome someone's taking the time to clean these up. 

I used a similar setup myself originally until moving over to a VM. The only versions of mongo work rather well, I will add some mentions of this to the new website. 

I've rewrote it all in vuejs so I apologize for not updating it with your alpine docker and attrib btw, I should have the new one done by the weekend so I will add it all in then.

**Comment by NotExpectedYet** [comment]
What would you like on the link back btw? I can put your GitHub or business if you have one.

**Pull request merged**
