### PR TITLE
Requesting a new alpine tag

### PR DESCRIPTION
**Pull request by torresmvl**
Greetings! I've started to develop an alpine build that i wonder if it could become a new tag for the project. Since one can use _**mongoDb Atlas**_ services, i've tried to compile an lean image that works with several architectures, including `amd64`:

- armhf
- aarch64
- i386

Tests ran sucessfuly on RPi B _v1.2_ and RPi _4_. Images uses _NodeJS v12.20.1 and NPM v6.14.10_ and weights roughly **160Mb**, user-ready deployment. They can be pulled from docker's registry [docker pull growlab/octofarm:latest](https://hub.docker.com/r/growlab/octofarm/)

@NotExpectedYet, please consider to accept at least the **.dockerignore**. OctoFarm official images are full of `.git` caching history therefore making the final image size quite bigger.
`# du -hd 1 /app` outputs from `octofarm/octofarm:latest`
```
40K     /app/.github
15M     /app/views
6.9M    /app/screenshots
548K    /app/server_src
8.0K    /app/config
24K     /app/.idea
5.1M    /app/client_src
56M     /app/.git
252K    /app/images
12K     /app/docker
84M     /app
```

I assume that are some improvements that would be nice to be developed over the main images:

- run as non-root user
- multi-stage build & multi-arch support

I would like to devote some time to make these improvements if there is interest. Thank you for this awesome application!

### CODE REVIEW

**Comment by NotExpectedYet** [comment]
Hey man I've only had a quick skim through but totally happy for this if people will use it. I'm a complete docker noob and most of what I have was pieced together from other users and their commits. Happy for the help with this totally. If you have more suggestions then feel free.

**Comment by torresmvl** [comment]
Nice! Will be cracking the nuts on my fork. Will start to scratch workflows and the documentation since it will be changing the mounting paths:

from | to
--- | ---
/app/logs | ~/app/logs
/scripts | ~/scripts
/app/images | ~/app/images

**Comment by NotExpectedYet** [comment]
Is there a dire need to change the paths? I'm going to be doing it for the 1.2 release so I'd rather not until then at the minute. Don't want to break current setups.

**Comment by torresmvl** [comment]
> Is there a dire need to change the paths? I'm going to be doing it for the 1.2 release so I'd rather not until then at the minute. Don't want to break current setups.

It's needed when one wants to run the application as a non-root user since this _newuser_ won't have permissions at `/` path level, and that effect is desirable for security reasons. In **alpine.Dockerfile**, user _**octofarm**_ is added, therefore the application now lives at `/home/octofarm/app` - pm2 is installed globally.
There are workarounds and i feel i could make the octofarm user's home path at ``/app`` and ``/scripts`` could be baked in Dockerfile giving octofarm's write/read/execute permissions. Didn't thought about that before...
what do you think?

**Comment by NotExpectedYet** [comment]
That sounds like it would suite us both so perfect :)

**Comment by torresmvl** [comment]
> That sounds like it would suite us both so perfect :)

Done! Paths are in agreement to yours original folder structure, see [commit 356118f](https://github.com/NotExpectedYet/OctoFarm/pull/233/commits/356118fa85c5b6fb0de837ea0b100fc050de2ea1).
If interested in testing these commits, updated images can be pulled at docker's registries: [docker pull growlab/octofarm:latest](https://hub.docker.com/r/growlab/octofarm/)

**Comment by NotExpectedYet** [comment]
> > That sounds like it would suite us both so perfect :)
> 
> Done! Paths are in agreement to yours original folder structure, see [commit 356118f](https://github.com/NotExpectedYet/OctoFarm/pull/233/commits/356118fa85c5b6fb0de837ea0b100fc050de2ea1).
> If interested in testing these commits, updated images can be pulled at docker's registries: [docker pull growlab/octofarm:latest](https://hub.docker.com/r/growlab/octofarm/)

Epic, I'll take a look through the week at them. Thanks for the work on this! 

I'll update the UnRaid tags as well once I've finalised these.

**Comment by NotExpectedYet** [comment]
Just want to mention I am going to check this out sorry man. Had some bare weird bugs to squash on the main code and haven't had chance yet.

**Comment by NotExpectedYet** [comment]
Totally up for migrating the others over to this format :)

**Comment by NotExpectedYet** [comment]
Added to my dockerhub, will do UnRaid in the morning my foods just arrived aha. 

Big thanks for those man, added it to the changelogs for 1.1.9 and will add your's to the website too with attribution for the PR.

**Comment by torresmvl** [comment]
Thank you for this application, mate! It's freakin awesome! Never have been so easy to manage those friendly robots :robot: 
I'm glad to help!

**Comment by torresmvl** [comment]
> Totally up for migrating the others over to this format :)

What do you mean? Update the others tags?

**Comment by NotExpectedYet** [comment]
> What do you mean? Update the others tags?

Yeah how you run them under and OctoFarm user rather than straight root. Think it would be good to bring them all in line together.

**Comment by NotExpectedYet** [comment]
> Thank you for this application, mate! It's freakin awesome! Never have been so easy to manage those friendly robots :robot: 
> I'm glad to help!

Your most welcome as well. I aim to clean up the code base next and turn it all into modules so will make it much easier for other developers to jump in going forward. I'm also aiming to support Etsy (and others) -> Print farm with the queues and jobs stuff I've got laid out. Seriously can't wait 😋

**Comment by torresmvl** [comment]
> Your most welcome as well. I aim to clean up the code base next and turn it all into modules so will make it much easier for other developers to jump in going forward. I'm also aiming to support Etsy (and others) -> Print farm with the queues and jobs stuff I've got laid out. Seriously can't wait

Wow! That's hot! Can't wait too. :octopus: 




> > What do you mean? Update the others tags?
> 
> Yeah how you run them under and OctoFarm user rather than straight root. Think it would be good to bring them all in line together.

Right, I'm assigning to that!

**Comment by NotExpectedYet** [comment]
Legend :D thank you!

**Comment by NotExpectedYet** [comment]
image

UnRaids on, just my snafu with the name. Updated will get pulled sometime today I think.

**Comment by torresmvl** [comment]
I'm already using `octofarm/octofarm:alpine-latest` :heart: 
Started to develop over the others images. Should I address next pull requests to `development` branch?

**Comment by NotExpectedYet** [comment]
Epic man, big thanks for these! 

Yeah that would be grand, was going to mention last time but it wasn't exactly breaking changes to anything that needed dire testing. All went well, I just need to double check the development branch as I hadn't back ported that before I did dockerhub links.

**Comment by NotExpectedYet** [comment]
@torresmvl Hello again! 

I've been working on V1.2 getting it ready and I'm now taking a look at the docker images. I wanted to simplify them. 

I see no point in having the main image and the alpine image. I would like alpine to superscede my original one what do you think? 

It would mean you pull from latest once that's released not alpine-latest. I will also re-do the monolithic container to follow your alpine changes with a user and such.

**Comment by torresmvl** [comment]
> I see no point in having the main image and the alpine image. I would like alpine to superscede my original one what do you think?

We surely can work on that! I agree with you.

> 
> It would mean you pull from latest once that's released not alpine-latest. I will also re-do the monolithic container to follow your alpine changes with a user and such.

 I'm quite sure there won't be any problems.
Starting right now.
I'll keep you noticed!

**Comment by NotExpectedYet** [comment]
> > I see no point in having the main image and the alpine image. I would like alpine to superscede my original one what do you think?
> 
> We surely can work on that! I agree with you.
> 
> > It would mean you pull from latest once that's released not alpine-latest. I will also re-do the monolithic container to follow your alpine changes with a user and such.
> 
> I'm quite sure there won't be any problems. Starting right now. I'll keep you noticed!

Is not done yet xD Will be when V1.2 hits master :) still some things to go through and sort out.

**Pull request merged**
