### PR TITLE
Add Mocha and dotenv

### PR DESCRIPTION
**Pull request by davidzwa**
Adds Mocha Sinon and Chai and test/assertion packages. Add example tests. Add dotenv package for mongo URL and other app settings

### CODE REVIEW

**Comment by NotExpectedYet** [comment]
Cheers! will take a look.

**Comment by davidzwa** [comment]
@NotExpectedYet could you enable the workflow I just added? This will report just like SonarCloud, and will take a couple of minutes to run each time.

**Comment by NotExpectedYet** [comment]
> @NotExpectedYet could you enable the workflow I just added? This will report just like SonarCloud, and will take a couple of minutes to run each time.

Yeah that's fine just give me a second to sort it. I'll get rid of SonarCloud did want to replace that.

**Comment by NotExpectedYet** [comment]
Sat, 13 Feb 2021 13:23:12 GMT | ERROR | OctoFarm-Server.log | MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string. | 


I get this error after that change

**Comment by NotExpectedYet** [comment]
You commented out the default db -_-

**Comment by davidzwa** [comment]
Facepalm, my bad

**Comment by davidzwa** [comment]
Oh you merged... that's maybe a bit too fast! Always check the changes :)

**Comment by NotExpectedYet** [comment]
> Oh you merged... that's maybe a bit too fast! Always check the changes :)

I'm good at doing that don't worry. I'm sure it loaded fine when I checked initially ahaha.

**Pull request merged**
